[package]
name = "eit-stream"
version = "0.1.0"
authors = ["Andrey Dyldin <and@cesbo.com>"]
build = "src/build.rs"
edition = "2018"

[dependencies]
error-rules = "0.2"
chrono = "0.4.6"
config = { path = "../libconfig" }
udp = { path = "../libudp" }
mpegts = { path = "../libmpegts" }
epg = { path = "../libepg" }

[profile.release]
panic = "abort"
opt-level = 3
lto = true
