[package]
name = "eit-stream"
version = "0.1.0"
authors = ["Andrey Dyldin <and@cesbo.com>"]

[dependencies]
getopts = "0.2"
chrono = "0.4.6"
socket = { path = "../libsocket" }
mpegts = { path = "../libmpegts" }
epg = { path = "../libepg" }

[profile.release]
panic = "abort"
opt-level = 3
lto = true
